---
- hosts: playground

  vars:
    PLAYGROUND_USER: "{{ lookup('env', 'USER') }}"
    VM_ADDRESS: "{{ groups['playground'][0] }}"
    REPO_NAME: playground

  tasks:
    #
    # Add user
    #
    - name: useradd {{ PLAYGROUND_USER }}
      user: name={{ PLAYGROUND_USER }} groups=sudo append=yes shell=/bin/bash

    - name: Make sudo not require a password
      lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

    - name: Ensure public key is in authorized_keys
      authorized_key:
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        user: "{{ PLAYGROUND_USER }}"

    #
    # Apt
    #
    - name: apt-get update
      apt: update_cache=yes
      # apt cache updates actually aren't all that meaningful, so ignore them in terms of change reporting
      changed_when: false

    - name: apt-get install apt https support
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common

    #
    # Required system dependencies for this playbook
    #
    - name: install dev dependencies
      apt:
        name:
          - git
          - unattended-upgrades

    - name: apply security upgrades
      command: unattended-upgrades --verbose
      changed_when: False

    - name: apt-get install pip3
      apt: name=python3-pip

    #
    # Setup Git server
    #
    - name: add git user
      user: name=git

    - name: create .ssh directory for git user
      file: path=/home/git/.ssh owner=git group=git mode=0700 state=directory

    - name: allow {{ PLAYGROUND_USER }} to access git server via ssh
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/git/.ssh/authorized_keys
        mode: 0600
        owner: git
        group: git

    - name: create directory for git repository
      file: path=/opt/git/{{ REPO_NAME }}.git owner=git group=git state=directory

    - name: create bare git repository
      become_user: git
      command: git init --bare /opt/git/{{ REPO_NAME }}.git
      args:
        creates: /opt/git/{{ REPO_NAME }}.git/HEAD
        warn: no

    #
    # Setup journald
    #
    - name: mkdir -p /etc/systemd/journald.conf.d
      file: path=/etc/systemd/journald.conf.d state=directory mode=0755

    - name: Configure journald to persist logs to disk
      copy:
        src: configs/custom.conf
        dest: /etc/systemd/journald.conf.d/
      notify: restart journald

    #
    # Setup Docker
    #
    - name: apt-key install docker key
      apt_key:
        id: 8D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Make configuration directory for Docker
      file: path=/etc/docker owner=root group=root mode=0770 state=directory

    - name: Create Docker daemon.json configuration file
      copy: src=configs/daemon.json dest=/etc/docker/daemon.json
      notify: restart docker

    - name: apt-add-repo https://download.docker.com/linux/ubuntu
      apt_repository:
        # temporarily hardcode 'bionic' as the distribution release until focal is available
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
        filename: docker

    # prevent unintentional docker upgrades
    - name: cp docker-engine /etc/apt/preferences.d/
      copy:
        dest: /etc/apt/preferences.d/docker-engine
        content: |
          Package: docker-ce
          Pin: version 5:19.03.8*
          Pin-Priority: 1002

    # install the pinned version of docker
    - name: apt-get install docker-ce
      apt:
        name: docker-ce
        state: latest
      register: docker_install

    - name: pip install docker
      pip: name=docker version=4.2.0

    - name: add users to docker group
      user: name={{ item }} groups=docker append=yes
      with_items:
        - '{{ PLAYGROUND_USER }}'
        - vagrant

    - name: enable memory cgroup and swap accounting for Docker
      replace:
        dest: /etc/default/grub
        regexp: (GRUB_CMDLINE_LINUX=").*(")
        replace: \1cgroup_enable=memory swapaccount=1\2
      register: grub_conf

    - name: update grub2 when grub config changed
      command: update-grub2
      when: grub_conf.changed

    - name: set reboot requested if grub config changed
      set_fact:
        reboot_requested: True
      when: grub_conf.changed

    #
    # Setup docker-gc
    #
    - name: install docker-gc in crontab
      cron:
        name: docker-gc
        minute: '0'
        hour: '*/2' # every 2 hours
        job: >
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock
          -v /etc:/etc -e GRACE_PERIOD_SECONDS=86400 spotify/docker-gc

    #
    # Setup cAdvisor
    #
    - name: launch cadvisor container
      docker_container:
        name: cadvisor
        image: google/cadvisor:v0.33.0
        restart_policy: always
        state: started
        memory: 256MB
        published_ports:
          - 8080:8080
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk/:/dev/disk:ro

    #
    # Reboot if needed
    #
    - name: Look for reasons to reboot
      shell: "test -e /var/run/reboot-required || grep -q '/lib[0-9]*/.* (deleted)$' /proc/*/maps && echo REBOOT"
      register: reboot_required
      failed_when: False
      changed_when: reboot_requested is defined or reboot_required.stdout == 'REBOOT'

    - name: reboot
      reboot: reboot_timeout=300
      when: reboot_required is not skipped and reboot_required.changed

    #
    # Clone applications
    #
    - name: push source to remote
      become: false
      local_action: >
        command warn="no" git push --all --force
          --repo git@{{ VM_ADDRESS }}:/opt/git/{{ REPO_NAME }}.git
      tags: deploy

    - name: clone source into working directory
      git:
        repo: /opt/git/{{ REPO_NAME }}.git/
        dest: /usr/src/{{ REPO_NAME }}/
      tags: deploy

    #
    # Setup Asterisk
    #
    - name: build Asterisk Docker image
      docker_image:
        name: asterisk
        path: /usr/src/{{ REPO_NAME }}/asterisk
        state: present
        force: yes
      tags: deploy

    - name: start Asterisk Docker container
      docker_container:
        name: asterisk
        image: asterisk
        state: started
        restart: yes
        restart_policy: always
        network_mode: host
      tags: deploy

    #
    # Setup swagger-ui
    #
    - name: build swagger-ui Docker image
      docker_image:
        name: swagger-ui
        path: /usr/src/{{ REPO_NAME }}/swagger-ui
        state: present
        force: yes
      tags: deploy

    - name: start swagger-ui Docker container
      docker_container:
        name: swagger-ui
        image: swagger-ui
        state: started
        restart: yes
        restart_policy: always
        published_ports:
          - 1337:80
        env:
          SWAGGER_URL: http://{{ inventory_hostname }}:8088/ari/api-docs/resources.json
          ARI_USERNAME: asterisk
          ARI_PASSWORD: asterisk
      tags: deploy

    #
    # Setup call-control
    #
    - name: build call-control Docker image
      docker_image:
        name: call-control
        path: /usr/src/{{ REPO_NAME }}/call-control
        state: present
        force: yes
      tags: deploy

    - name: start call-control Docker container
      docker_container:
        name: call-control
        image: call-control
        state: started
        restart: yes
        restart_policy: always
        network_mode: host
        env:
          NODE_ENV: production
          DEBUG: '*'
      tags: deploy

  handlers:
    - name: restart cAdvisor
      service: name=cadvisor state=restarted

    - name: restart docker
      service: name=docker state=restarted
      when: docker_install is not defined or not docker_install.changed

    - name: restart journald
      service: name=systemd-journald state=restarted
