---
# we have a history of single quotes, so stick with that
singleQuote: true
# prose wrap helps formatting Markdown and YAML
proseWrap: always
# vim-prettier has its own defaults, so we need to reset anything that doesn't match
trailingComma: es5
arrowParens: always
